#!/usr/bin/env python

# Copyright (c) 2009, Tom Adams
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

import tempfile, os, subprocess, sys

if __name__ == "__main__":
    tmp = tempfile.mkdtemp()

    # Convert to WAV
    outfiles = []
    n = 1
    for file in sys.argv[1:]:
        out = tmp+('/%03d.wav'%n)
        if subprocess.call(['mplayer', file, '-ao', 'pcm:waveheader:file="'+out+'"']):
            raise Exception('mplayer failed')
        outfiles.append(out)
        n += 1

    # Burn
    cdrecord = ['cdrecord', '-pad', '-audio'] + outfiles
    if subprocess.call(cdrecord):
        raise Exception('cdrecord failed')

    # Clean-up
    for f in outfiles:
        os.remove(f)
    os.rmdir(tmp)
